---
title: "CSX415_Project_airline_performance"
author: "Ajey Patil"
date: "5/7/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
### Data Cleaning done while  load.project

```{r load project}
currdir <- getwd()
library(ProjectTemplate)
load.project()
```
## Install Packages

```{r install packages}
devtools::install_github("ajeypatil/rmse")
library(rmse)
```

## Perform Exploratory Data Analysis
#### graphs stored in graph directory

```{r Perform Exploratory Data Analysis : graphs stored in graph directory}
source('src/CSX415_Project_ExploratoryDataAnalysis.R')
rm(cancellationsdb)
rm(flights)
rm(allcancellations)
rm(alldelays)
rm(cancellationsagg)
```
## Modelling
#### PreProcess Data
#### Remove zero variance columns
#### Test-Train split
#### Apply Model

```{r Modelling}
# Convert to categorial variable
delaysdb$AIRLINE <- factor(delaysdb$AIRLINE) 

preProcessDb <- preProcess(delaysdb, method=c("medianImpute","nzv","center", "scale"))
delaysdb <- predict(preProcessDb,delaysdb)

delaysdb <- delaysdb[sample(nrow(delaysdb)),]

b <- createDataPartition(delaysdb$AIRLINE_DELAY, p = 0.8, list=FALSE)
TrainData    <- delaysdb[b,]
TestData     <- delaysdb[-b,]

# Naive Bayes model
# This model cannot be used for regression
# source('src/models/CSX415_Project_Data_Model_Naive.R')
       
# Linear model
source('src/models/CSX415_Project_Data_Model_Linear.R')

# Tree
#source('src/models/CSX415_Project_Data_Model_Tree.R')

# Generialised Linear Model
#source('src/models/CSX415_Project_Data_Model_glmnet.R')

```
