---
title: "Assets"
author: "Ajey Patil"
date: "4/24/2018"
output: html_document
---

# Assets for Airline Flight Delays And Cancellations Analysis

## Performance Analysis (complete run)
* CSX415_Project_airline_performance.Rmd *

## Input
### FORMAL PROBLEM STATEMENT
* docs/CSX415_Project_Formal_Problem_Statment.Rmd *

### Data
#### Flight data
https://www.kaggle.com/usdot/flight-delays/data

* Flights database : flights.csv *
* Airlines database : airlines.csv *
* Airports database : airports.csv *

#### Weather Data
https://www.ncdc.noaa.gov/orders/qclcd/,
This source contains hourly weather data at various airports.

## Code

###  Running code
* src *

### Exploratory Data Analysis 
* src/01-EDA/CSX415_Project_ExploratoryDataAnalysis.R *

### Data PreProcess
* src/02-PREPROCESS/CSX415_Project_preprocess.R *

###  Working models
* src/03-MODELS *
* src/03-MODELS/CSX415_Project_Data_Model_Linear.R *
* src/03-MODELS/CSX415_Project_Data_Model_Tree.R *
* src/03-MODELS/CSX415_Project_Data_Model_glmnet.R *

###  Code dependendcies
* lib *

### Pkgs
* pkgs/rmse *

## Outputs
### Performance report
* reports/CSX415_Project_Airline_performance_report.md *

### Observations
* reports/CSX415_Project_Modelling_Analysis_Obervations.md *
* graphs/CSX415_Project_Data_visualizations *

#### MODEL PERFORMANCE EVALS
* reports/Model_Performance/CSX415_Project_Data_model-performance-naive.md *
* reports/Model_Performance/CSX415_Project_Data_model-performance-linear.md *
* reports/Model_Performance/CSX415_Project_Data_model-performance-tree.md *

#### MODEL PREDICTION REPORTS
* reports/Model_Performance/CSX415_Project_Data_model-prediction-naive.md *
* reports/Model_Performance/CSX415_Project_Data_model-prediction-linear.md *
* reports/Model_Performance/CSX415_Project_Data_model-prediction-tree.md *

### Instructions
#### Deployment instructions
* deploy/CSX415_Project_Deploy_instructions.md *

#### Deployment code
* deploy/src *

#### Maintainence Code
* maintain/src *

#### Maintainence instructions 
* maintain/CSX415_Project_Deploy_maintian.md *

